services:
  7eminar-mysql:
    container_name: 7eminar-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 7eminar
      MYSQL_ROOT_HOST: '%'
    ports:
      - 63306:3306
    networks:
      - app-network

  7eminar-php-fpm:
    container_name: 7eminar-php-fpm
    restart: always
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./php-fpm
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - 7eminar-mysql
      - 7eminar-redis
    volumes:
      - ${PROJECT_DIR}:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "15173:5173"
    networks:
      - app-network

  7eminar-nginx:
    container_name: 7eminar-nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${PROJECT_DIR}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - 7eminar-php-fpm
    ports:
      - "8008:80"
    networks:
      - app-network

  7eminar-redis:
    image: redis:alpine
    container_name: 7eminar-redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - app-network

  7eminar-elasticsearch:
    container_name: 7eminar-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - cluster.routing.allocation.disk.watermark.low=90%
      - cluster.routing.allocation.disk.watermark.high=95%
      - cluster.routing.allocation.disk.watermark.flood_stage=97%
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
    app-network:
      driver: bridge